package com.qrencia.subscription.category;

import java.util.List;

import com.qrencia.subscription.service.Service;
import com.qrencia.subscription.tier.Tier;

import jakarta.persistence.*;
import lombok.*;


@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Categories")
public class Category {
    // Attributes:

    // category_id: Integer (Primary Key, Auto-increment)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer categoryId;

    // name: String
    @Column(nullable = false, unique = true)
    private String name;

    @ManyToMany(mappedBy = "categories", fetch = FetchType.LAZY)
    private List<Tier> tiers;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "Category_Services",
        joinColumns = @JoinColumn(name = "category_id"),
        inverseJoinColumns = @JoinColumn(name = "service_id")
    )
    private List<Service> services;

    // Methods:

    // public Integer getCategoryId() → Retrieves the category ID.

    // public String getName() → Gets the category name.

    // public void setName(String name) → Updates the category name.

    // public List<Tier> getTiers() → Gets the tiers linked to this category.

    // public void setTiers(List<Tier> tiers) → Associates tiers with this category.

    // public List<Service> getServices() → Retrieves related services.

    // public void setServices(List<Service> services) → Assigns services.
}
// Note: The methods mentioned in the comments are automatically generated by Lombok's @Data annotation.
// The @Data annotation generates getters, setters, toString, equals, and hashCode methods.
// The @Entity annotation indicates that this class is a JPA entity.